// <auto-generated />
using System;
using DrawnFromSteel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DrawnFromSteel.Migrations
{
    [DbContext(typeof(DFSContext))]
    [Migration("20241219023911_EmailVerifiedNullable")]
    partial class EmailVerifiedNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrawnFromSteel.Models.Auth.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<int>("ExpiresAt")
                        .HasColumnType("integer")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_token");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_account_id");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("SessionState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_state");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_account_user_id");

                    b.HasIndex("ProviderAccountId", "Provider")
                        .HasDatabaseName("ix_account_provider_account_id_provider");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Auth.Session", b =>
                {
                    b.Property<string>("SessionToken")
                        .HasColumnType("text")
                        .HasColumnName("session_token");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("SessionToken")
                        .HasName("pk_session");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_session_user_id");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Static.Ancestry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("SizeModifier")
                        .HasColumnType("integer")
                        .HasColumnName("size_modifier");

                    b.Property<int>("SizeSquares")
                        .HasColumnType("integer")
                        .HasColumnName("size_squares");

                    b.Property<int>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<string>("SubType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sub_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_ancestry");

                    b.ToTable("ancestry", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Devil"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Dragon Knight"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Dwarf"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 6,
                            SubType = "Wode",
                            Type = "Elf"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "High",
                            Type = "Elf"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            SizeModifier = 3,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Hakaan"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Human"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Memonek"
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Orc"
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            SizeModifier = 1,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Polder"
                        },
                        new
                        {
                            Id = 11,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Revenant"
                        },
                        new
                        {
                            Id = 12,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Time Raider"
                        });
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Static.Skill.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SkillGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_group_id");

                    b.HasKey("Id")
                        .HasName("pk_skill");

                    b.HasIndex("SkillGroupId")
                        .HasDatabaseName("ix_skill_skill_group_id");

                    b.ToTable("skill", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Make bombs and potions",
                            Name = "Alchemy",
                            SkillGroupId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Create buildings and vehicles",
                            Name = "Architecture",
                            SkillGroupId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Forge metal armor and weapons",
                            Name = "Blacksmithing",
                            SkillGroupId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Make ranged weapons and ammunition",
                            Name = "Fletching",
                            SkillGroupId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Create false badges, documents, and other items",
                            Name = "Forgery",
                            SkillGroupId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Create bracelets, crowns, rings, and other jewelry",
                            Name = "Jewelry",
                            SkillGroupId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Build machines and clockwork items",
                            Name = "Mechanics",
                            SkillGroupId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Craft cloth and leather clothing",
                            Name = "Tailoring",
                            SkillGroupId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Move up vertical surfaces",
                            Name = "Climb",
                            SkillGroupId = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Control vehicles",
                            Name = "Drive",
                            SkillGroupId = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "Remain engaged in strenuous activity over a long period of time",
                            Name = "Endurance",
                            SkillGroupId = 2
                        },
                        new
                        {
                            Id = 12,
                            Description = "Move across unsteady or narrow surfaces, and tumble",
                            Name = "Gymnastics",
                            SkillGroupId = 2
                        },
                        new
                        {
                            Id = 13,
                            Description = "Use mundane first aid",
                            Name = "Heal",
                            SkillGroupId = 2
                        },
                        new
                        {
                            Id = 14,
                            Description = "Leap vertical and horizontal distances",
                            Name = "Jump",
                            SkillGroupId = 2
                        },
                        new
                        {
                            Id = 15,
                            Description = "Pick up, carry, and throw heavy objects",
                            Name = "Lift",
                            SkillGroupId = 2
                        },
                        new
                        {
                            Id = 16,
                            Description = "Read a map and travel without becoming lost",
                            Name = "Navigate",
                            SkillGroupId = 2
                        },
                        new
                        {
                            Id = 17,
                            Description = "Ride and control a mount who isn’t sapient, such as a horse",
                            Name = "Ride",
                            SkillGroupId = 2
                        },
                        new
                        {
                            Id = 18,
                            Description = "Move through deep liquid",
                            Name = "Swim",
                            SkillGroupId = 2
                        },
                        new
                        {
                            Id = 19,
                            Description = "Impress others with stories of your deeds",
                            Name = "Brag",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 20,
                            Description = "Relate to someone on a personal level",
                            Name = "Empathize",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 21,
                            Description = "Attract romantic attention from someone",
                            Name = "Flirt",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 22,
                            Description = "Make bets with others",
                            Name = "Gamble",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 23,
                            Description = "Interact with animal wildlife that isn’t sapient",
                            Name = "Handle Animals",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 24,
                            Description = "Obtain information from a creature withholding it",
                            Name = "Interrogate",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 25,
                            Description = "Awe or scare a creature",
                            Name = "Intimidate",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 26,
                            Description = "Inspire people to action",
                            Name = "Lead",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 27,
                            Description = "Convince someone that a falsehood is true",
                            Name = "Lie",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 28,
                            Description = "Perform music vocally or with an instrument",
                            Name = "Music",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 29,
                            Description = "Engage in dance, oratory, acting, or some other physical performance",
                            Name = "Perform",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 30,
                            Description = "Convince someone to agree with you through use of your charms and grace",
                            Name = "Persuade",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 31,
                            Description = "Read the emotions and body language of other creatures",
                            Name = "Read Person",
                            SkillGroupId = 3
                        },
                        new
                        {
                            Id = 32,
                            Description = "Intuitively sense the details of your surroundings",
                            Name = "Alertness",
                            SkillGroupId = 4
                        },
                        new
                        {
                            Id = 33,
                            Description = "Hide an object on your person or in your environment",
                            Name = "Conceal Object",
                            SkillGroupId = 4
                        },
                        new
                        {
                            Id = 34,
                            Description = "Change your appearance to look like a different person",
                            Name = "Disguise",
                            SkillGroupId = 4
                        },
                        new
                        {
                            Id = 35,
                            Description = "Actively listen to something that is hard to hear, such as a whispered conversation through a door",
                            Name = "Eavesdrop",
                            SkillGroupId = 4
                        },
                        new
                        {
                            Id = 36,
                            Description = "Escape from bonds such as rope or manacles",
                            Name = "Escape Artist",
                            SkillGroupId = 4
                        },
                        new
                        {
                            Id = 37,
                            Description = "Conceal yourself from others’ observation",
                            Name = "Hide",
                            SkillGroupId = 4
                        },
                        new
                        {
                            Id = 38,
                            Description = "Open a lock without using the key",
                            Name = "Pick Lock",
                            SkillGroupId = 4
                        },
                        new
                        {
                            Id = 39,
                            Description = "Steal an item that another person wears or carries without them noticing",
                            Name = "Pick Pocket",
                            SkillGroupId = 4
                        },
                        new
                        {
                            Id = 40,
                            Description = "Disable a mechanical device such as a trap",
                            Name = "Sabotage",
                            SkillGroupId = 4
                        },
                        new
                        {
                            Id = 41,
                            Description = "Actively search an environment for important details and items",
                            Name = "Search",
                            SkillGroupId = 4
                        },
                        new
                        {
                            Id = 42,
                            Description = "Move silently",
                            Name = "Sneak",
                            SkillGroupId = 4
                        },
                        new
                        {
                            Id = 43,
                            Description = "Follow a trail that another creature has left behind",
                            Name = "Track",
                            SkillGroupId = 4
                        },
                        new
                        {
                            Id = 44,
                            Description = "Knowing about a culture’s customs, folktales, and taboos",
                            Name = "Culture",
                            SkillGroupId = 5
                        },
                        new
                        {
                            Id = 45,
                            Description = "Knowing about criminal organizations, their crimes, their relationships, and their leaders",
                            Name = "Criminal Underworld",
                            SkillGroupId = 5
                        },
                        new
                        {
                            Id = 46,
                            Description = "Knowing about significant past events",
                            Name = "History",
                            SkillGroupId = 5
                        },
                        new
                        {
                            Id = 47,
                            Description = "Knowing about magical places, spells, rituals, items, and phenomena",
                            Name = "Magic",
                            SkillGroupId = 5
                        },
                        new
                        {
                            Id = 48,
                            Description = "Knowing monster ecology, strengths, and weaknesses",
                            Name = "Monsters",
                            SkillGroupId = 5
                        },
                        new
                        {
                            Id = 49,
                            Description = "Knowing about natural flora, fauna, and weather",
                            Name = "Nature",
                            SkillGroupId = 5
                        },
                        new
                        {
                            Id = 50,
                            Description = "Knowing about psionic places, spells, rituals, items, and phenomena",
                            Name = "Psionics",
                            SkillGroupId = 5
                        },
                        new
                        {
                            Id = 51,
                            Description = "Knowing about religious mythology, practices, and rituals",
                            Name = "Religion",
                            SkillGroupId = 5
                        },
                        new
                        {
                            Id = 52,
                            Description = "Knowing gossip, legends, and uncertain truths",
                            Name = "Rumors",
                            SkillGroupId = 5
                        },
                        new
                        {
                            Id = 53,
                            Description = "Knowing noble etiquette and the leadership and power dynamics of noble families",
                            Name = "Society",
                            SkillGroupId = 5
                        },
                        new
                        {
                            Id = 54,
                            Description = "Knowing about the various planets of the timescape",
                            Name = "Timescape",
                            SkillGroupId = 5
                        });
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Static.Skill.SkillGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_skill_group");

                    b.ToTable("skill_group", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Skills from the crafting skill group are used in the creation and appraisal of goods and for jury-rigging contraptions. They are especially useful during rests and downtime.",
                            Name = "Crafting"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Skills from the exploration skill group are used to physically explore the environment around the characters, and to overcome physical obstacles.",
                            Name = "Exploration"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Skills from the interpersonal skill group are used to socially interact with other creatures, and are particularly useful during negotiations. Aside from the Handle Animals skill, you can generally only use interpersonal skills when you attempt to influence creatures who have emotions and who can understand you.",
                            Name = "Interpersonal"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Skills from the intrigue skill group are used in tasks centered around investigation, thievery, and spycraft.",
                            Name = "Intrigue"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Skills from the lore skill group are used to research and recall specific information. They are especially useful during rests and downtime.",
                            Name = "Lore"
                        });
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Static.Skill.SkillOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_skill_option");

                    b.ToTable("skill_option", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "One skill from the exploration or interpersonal skill groups.",
                            Name = "env-nomadic"
                        },
                        new
                        {
                            Id = 2,
                            Description = "One skill from the crafting or lore skill groups.",
                            Name = "env-rural"
                        },
                        new
                        {
                            Id = 3,
                            Description = "One skill from the interpersonal or lore skill groups.",
                            Name = "env-secluded"
                        },
                        new
                        {
                            Id = 4,
                            Description = "One skill from the interpersonal or intrigue skill groups.",
                            Name = "env-urban"
                        },
                        new
                        {
                            Id = 5,
                            Description = "One skill from the crafting or exploration skill groups.",
                            Name = "env-wilderness"
                        },
                        new
                        {
                            Id = 6,
                            Description = "One skill from the exploration or intrigue skill groups.",
                            Name = "org-anarchic"
                        },
                        new
                        {
                            Id = 7,
                            Description = "One skill from the intrigue or lore skill groups.",
                            Name = "org-bureaucratic"
                        },
                        new
                        {
                            Id = 8,
                            Description = "One skill from the crafting or interpersonal skill groups.",
                            Name = "org-communal"
                        },
                        new
                        {
                            Id = 9,
                            Description = "One skill from the lore skill group.",
                            Name = "upb-academic"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The Music or Perform skill, or one skill from the crafting skill group.",
                            Name = "upb-creative"
                        },
                        new
                        {
                            Id = 11,
                            Description = "One skill from the intrigue skill group.",
                            Name = "upb-illegal"
                        },
                        new
                        {
                            Id = 12,
                            Description = "One of the Blacksmithing or Handle Animals skills, or one skill from the exploration skill group.",
                            Name = "upb-labor"
                        },
                        new
                        {
                            Id = 13,
                            Description = " One of the Alertness, Blacksmithing, Climb, Endurance, Fletching, Intimidate, Jump, Monsters, Ride, or Track skills.",
                            Name = "upb-martial"
                        },
                        new
                        {
                            Id = 14,
                            Description = "One skill from the interpersonal skill group.",
                            Name = "upb-noble"
                        },
                        new
                        {
                            Id = 15,
                            Description = " Two skills from the crafting skill group.",
                            Name = "car-artisan"
                        },
                        new
                        {
                            Id = 16,
                            Description = "The Criminal Underworld skill, plus two skills from the intrigue skill group.",
                            Name = "car-criminal"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Two skills from the exploration skill group.",
                            Name = "car-gladiator"
                        },
                        new
                        {
                            Id = 18,
                            Description = "The Endurance skill, plus choose any two skills from Blacksmithing or the skills of the exploration skill group.",
                            Name = "car-laborer"
                        },
                        new
                        {
                            Id = 19,
                            Description = "The Magic skill, plus two skills from the lore skill group.",
                            Name = "car-magesapprentice"
                        },
                        new
                        {
                            Id = 20,
                            Description = "The Music or Performance skill, plus two skills from the interpersonal skill group.",
                            Name = "car-performer"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Two skills from the lore skill group.",
                            Name = "car-sage"
                        },
                        new
                        {
                            Id = 22,
                            Description = "One skill from each of the exploration skill group and the intrigue skill group.",
                            Name = "car-soldier"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Choose any two skills from the interpersonal or lore skill groups.",
                            Name = "cls-conduit"
                        },
                        new
                        {
                            Id = 24,
                            Description = "You gain Magic and can choose any three skills from the crafting or lore skill groups.",
                            Name = "cls-elementalist"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Nature, plus choose any two skills from the exploration or intrigue skill groups.",
                            Name = "cls-fury"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Hide and Sneak, plus choose any five skills from Criminal Underworld or the skills of the exploration, interpersonal, or intrigue skill groups.",
                            Name = "cls-shadow"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Lead, plus choose any two skills from Alertness, Architecture, Blacksmithing, Brag, Culture, Empathize, Fletching, History, Mechanics, Monsters, Search, or the skills of the exploration skill group.",
                            Name = "cls-tactician"
                        });
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Static.Skill.SkillOptionPool", b =>
                {
                    b.Property<int>("SkillOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_option_id");

                    b.Property<int>("SkillPoolId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_pool_id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.HasKey("SkillOptionId", "SkillPoolId")
                        .HasName("pk_skill_option_pool");

                    b.HasIndex("SkillPoolId")
                        .HasDatabaseName("ix_skill_option_pool_skill_pool_id");

                    b.ToTable("skill_option_pool", (string)null);

                    b.HasData(
                        new
                        {
                            SkillOptionId = 1,
                            SkillPoolId = 1,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 2,
                            SkillPoolId = 2,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 3,
                            SkillPoolId = 3,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 4,
                            SkillPoolId = 4,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 5,
                            SkillPoolId = 5,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 6,
                            SkillPoolId = 6,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 7,
                            SkillPoolId = 7,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 8,
                            SkillPoolId = 8,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 9,
                            SkillPoolId = 9,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 10,
                            SkillPoolId = 10,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 11,
                            SkillPoolId = 11,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 12,
                            SkillPoolId = 12,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 13,
                            SkillPoolId = 13,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 14,
                            SkillPoolId = 14,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 15,
                            SkillPoolId = 15,
                            Count = 2
                        },
                        new
                        {
                            SkillOptionId = 16,
                            SkillPoolId = 16,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 16,
                            SkillPoolId = 17,
                            Count = 2
                        },
                        new
                        {
                            SkillOptionId = 17,
                            SkillPoolId = 18,
                            Count = 2
                        },
                        new
                        {
                            SkillOptionId = 18,
                            SkillPoolId = 19,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 18,
                            SkillPoolId = 20,
                            Count = 2
                        },
                        new
                        {
                            SkillOptionId = 19,
                            SkillPoolId = 21,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 19,
                            SkillPoolId = 22,
                            Count = 2
                        },
                        new
                        {
                            SkillOptionId = 20,
                            SkillPoolId = 23,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 20,
                            SkillPoolId = 24,
                            Count = 2
                        },
                        new
                        {
                            SkillOptionId = 21,
                            SkillPoolId = 25,
                            Count = 2
                        },
                        new
                        {
                            SkillOptionId = 22,
                            SkillPoolId = 26,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 22,
                            SkillPoolId = 27,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 23,
                            SkillPoolId = 28,
                            Count = 2
                        },
                        new
                        {
                            SkillOptionId = 24,
                            SkillPoolId = 29,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 24,
                            SkillPoolId = 30,
                            Count = 3
                        },
                        new
                        {
                            SkillOptionId = 25,
                            SkillPoolId = 31,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 25,
                            SkillPoolId = 32,
                            Count = 2
                        },
                        new
                        {
                            SkillOptionId = 26,
                            SkillPoolId = 33,
                            Count = 2
                        },
                        new
                        {
                            SkillOptionId = 26,
                            SkillPoolId = 34,
                            Count = 5
                        },
                        new
                        {
                            SkillOptionId = 27,
                            SkillPoolId = 35,
                            Count = 1
                        },
                        new
                        {
                            SkillOptionId = 27,
                            SkillPoolId = 36,
                            Count = 2
                        });
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Static.Skill.SkillPool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_skill_pool");

                    b.ToTable("skill_pool", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "env-nomadic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "env-rural"
                        },
                        new
                        {
                            Id = 3,
                            Name = "env-secluded"
                        },
                        new
                        {
                            Id = 4,
                            Name = "env-urban"
                        },
                        new
                        {
                            Id = 5,
                            Name = "env-wilderness"
                        },
                        new
                        {
                            Id = 6,
                            Name = "org-anarchic"
                        },
                        new
                        {
                            Id = 7,
                            Name = "org-bureaucratic"
                        },
                        new
                        {
                            Id = 8,
                            Name = "org-communal"
                        },
                        new
                        {
                            Id = 9,
                            Name = "upb-academic"
                        },
                        new
                        {
                            Id = 10,
                            Name = "upb-creative"
                        },
                        new
                        {
                            Id = 11,
                            Name = "upb-illegal"
                        },
                        new
                        {
                            Id = 12,
                            Name = "upb-labor"
                        },
                        new
                        {
                            Id = 13,
                            Name = "upb-martial"
                        },
                        new
                        {
                            Id = 14,
                            Name = "upb-noble"
                        },
                        new
                        {
                            Id = 15,
                            Name = "car-artisan"
                        },
                        new
                        {
                            Id = 16,
                            Name = "car-criminal-1"
                        },
                        new
                        {
                            Id = 17,
                            Name = "car-criminal-2"
                        },
                        new
                        {
                            Id = 18,
                            Name = "car-gladiator"
                        },
                        new
                        {
                            Id = 19,
                            Name = "car-laborer-1"
                        },
                        new
                        {
                            Id = 20,
                            Name = "car-laborer-2"
                        },
                        new
                        {
                            Id = 21,
                            Name = "car-magesapprentice-1"
                        },
                        new
                        {
                            Id = 22,
                            Name = "car-magesapprentice-2"
                        },
                        new
                        {
                            Id = 23,
                            Name = "car-performer-1"
                        },
                        new
                        {
                            Id = 24,
                            Name = "car-performer-2"
                        },
                        new
                        {
                            Id = 25,
                            Name = "car-sage"
                        },
                        new
                        {
                            Id = 26,
                            Name = "car-soldier-1"
                        },
                        new
                        {
                            Id = 27,
                            Name = "car-soldier-2"
                        },
                        new
                        {
                            Id = 28,
                            Name = "cls-conduit"
                        },
                        new
                        {
                            Id = 29,
                            Name = "cls-elementalist-1"
                        },
                        new
                        {
                            Id = 30,
                            Name = "cls-elementalist-2"
                        },
                        new
                        {
                            Id = 31,
                            Name = "cls-fury-1"
                        },
                        new
                        {
                            Id = 32,
                            Name = "cls-fury-2"
                        },
                        new
                        {
                            Id = 33,
                            Name = "cls-shadow-1"
                        },
                        new
                        {
                            Id = 34,
                            Name = "cls-shadow-2"
                        },
                        new
                        {
                            Id = 35,
                            Name = "cls-tactician-1"
                        },
                        new
                        {
                            Id = 36,
                            Name = "cls-tactician-2"
                        });
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Transient.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_hero");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_hero_user_id");

                    b.ToTable("hero", (string)null);
                });

            modelBuilder.Entity("SkillPoolSkill", b =>
                {
                    b.Property<int>("SkillPoolId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_pool_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.HasKey("SkillPoolId", "SkillId")
                        .HasName("pk_skill_pool_skill");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_skill_pool_skill_skill_id");

                    b.ToTable("skill_pool_skill", (string)null);

                    b.HasData(
                        new
                        {
                            SkillPoolId = 10,
                            SkillId = 28
                        },
                        new
                        {
                            SkillPoolId = 10,
                            SkillId = 29
                        },
                        new
                        {
                            SkillPoolId = 12,
                            SkillId = 3
                        },
                        new
                        {
                            SkillPoolId = 12,
                            SkillId = 23
                        },
                        new
                        {
                            SkillPoolId = 13,
                            SkillId = 32
                        },
                        new
                        {
                            SkillPoolId = 13,
                            SkillId = 3
                        },
                        new
                        {
                            SkillPoolId = 13,
                            SkillId = 9
                        },
                        new
                        {
                            SkillPoolId = 13,
                            SkillId = 11
                        },
                        new
                        {
                            SkillPoolId = 13,
                            SkillId = 4
                        },
                        new
                        {
                            SkillPoolId = 13,
                            SkillId = 25
                        },
                        new
                        {
                            SkillPoolId = 13,
                            SkillId = 14
                        },
                        new
                        {
                            SkillPoolId = 13,
                            SkillId = 48
                        },
                        new
                        {
                            SkillPoolId = 13,
                            SkillId = 17
                        },
                        new
                        {
                            SkillPoolId = 13,
                            SkillId = 43
                        },
                        new
                        {
                            SkillPoolId = 16,
                            SkillId = 45
                        },
                        new
                        {
                            SkillPoolId = 19,
                            SkillId = 11
                        },
                        new
                        {
                            SkillPoolId = 20,
                            SkillId = 3
                        },
                        new
                        {
                            SkillPoolId = 21,
                            SkillId = 47
                        },
                        new
                        {
                            SkillPoolId = 23,
                            SkillId = 28
                        },
                        new
                        {
                            SkillPoolId = 23,
                            SkillId = 29
                        },
                        new
                        {
                            SkillPoolId = 29,
                            SkillId = 47
                        },
                        new
                        {
                            SkillPoolId = 31,
                            SkillId = 49
                        },
                        new
                        {
                            SkillPoolId = 33,
                            SkillId = 37
                        },
                        new
                        {
                            SkillPoolId = 33,
                            SkillId = 42
                        },
                        new
                        {
                            SkillPoolId = 34,
                            SkillId = 45
                        },
                        new
                        {
                            SkillPoolId = 35,
                            SkillId = 26
                        },
                        new
                        {
                            SkillPoolId = 36,
                            SkillId = 32
                        },
                        new
                        {
                            SkillPoolId = 36,
                            SkillId = 2
                        },
                        new
                        {
                            SkillPoolId = 36,
                            SkillId = 3
                        },
                        new
                        {
                            SkillPoolId = 36,
                            SkillId = 19
                        },
                        new
                        {
                            SkillPoolId = 36,
                            SkillId = 44
                        },
                        new
                        {
                            SkillPoolId = 36,
                            SkillId = 20
                        },
                        new
                        {
                            SkillPoolId = 36,
                            SkillId = 4
                        },
                        new
                        {
                            SkillPoolId = 36,
                            SkillId = 46
                        },
                        new
                        {
                            SkillPoolId = 36,
                            SkillId = 7
                        },
                        new
                        {
                            SkillPoolId = 36,
                            SkillId = 48
                        },
                        new
                        {
                            SkillPoolId = 36,
                            SkillId = 41
                        });
                });

            modelBuilder.Entity("SkillPoolSkillGroup", b =>
                {
                    b.Property<int>("SkillPoolId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_pool_id");

                    b.Property<int>("SkillGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_group_id");

                    b.HasKey("SkillPoolId", "SkillGroupId")
                        .HasName("pk_skill_pool_skill_group");

                    b.HasIndex("SkillGroupId")
                        .HasDatabaseName("ix_skill_pool_skill_group_skill_group_id");

                    b.ToTable("skill_pool_skill_group", (string)null);

                    b.HasData(
                        new
                        {
                            SkillPoolId = 1,
                            SkillGroupId = 2
                        },
                        new
                        {
                            SkillPoolId = 1,
                            SkillGroupId = 3
                        },
                        new
                        {
                            SkillPoolId = 2,
                            SkillGroupId = 1
                        },
                        new
                        {
                            SkillPoolId = 2,
                            SkillGroupId = 5
                        },
                        new
                        {
                            SkillPoolId = 3,
                            SkillGroupId = 3
                        },
                        new
                        {
                            SkillPoolId = 3,
                            SkillGroupId = 5
                        },
                        new
                        {
                            SkillPoolId = 4,
                            SkillGroupId = 3
                        },
                        new
                        {
                            SkillPoolId = 4,
                            SkillGroupId = 4
                        },
                        new
                        {
                            SkillPoolId = 5,
                            SkillGroupId = 1
                        },
                        new
                        {
                            SkillPoolId = 5,
                            SkillGroupId = 2
                        },
                        new
                        {
                            SkillPoolId = 6,
                            SkillGroupId = 2
                        },
                        new
                        {
                            SkillPoolId = 6,
                            SkillGroupId = 4
                        },
                        new
                        {
                            SkillPoolId = 7,
                            SkillGroupId = 4
                        },
                        new
                        {
                            SkillPoolId = 7,
                            SkillGroupId = 5
                        },
                        new
                        {
                            SkillPoolId = 8,
                            SkillGroupId = 1
                        },
                        new
                        {
                            SkillPoolId = 8,
                            SkillGroupId = 3
                        },
                        new
                        {
                            SkillPoolId = 9,
                            SkillGroupId = 5
                        },
                        new
                        {
                            SkillPoolId = 10,
                            SkillGroupId = 1
                        },
                        new
                        {
                            SkillPoolId = 11,
                            SkillGroupId = 4
                        },
                        new
                        {
                            SkillPoolId = 12,
                            SkillGroupId = 2
                        },
                        new
                        {
                            SkillPoolId = 14,
                            SkillGroupId = 3
                        },
                        new
                        {
                            SkillPoolId = 15,
                            SkillGroupId = 1
                        },
                        new
                        {
                            SkillPoolId = 17,
                            SkillGroupId = 4
                        },
                        new
                        {
                            SkillPoolId = 18,
                            SkillGroupId = 2
                        },
                        new
                        {
                            SkillPoolId = 20,
                            SkillGroupId = 2
                        },
                        new
                        {
                            SkillPoolId = 22,
                            SkillGroupId = 5
                        },
                        new
                        {
                            SkillPoolId = 24,
                            SkillGroupId = 3
                        },
                        new
                        {
                            SkillPoolId = 25,
                            SkillGroupId = 5
                        },
                        new
                        {
                            SkillPoolId = 26,
                            SkillGroupId = 2
                        },
                        new
                        {
                            SkillPoolId = 27,
                            SkillGroupId = 4
                        },
                        new
                        {
                            SkillPoolId = 28,
                            SkillGroupId = 3
                        },
                        new
                        {
                            SkillPoolId = 28,
                            SkillGroupId = 5
                        },
                        new
                        {
                            SkillPoolId = 30,
                            SkillGroupId = 1
                        },
                        new
                        {
                            SkillPoolId = 30,
                            SkillGroupId = 5
                        },
                        new
                        {
                            SkillPoolId = 32,
                            SkillGroupId = 2
                        },
                        new
                        {
                            SkillPoolId = 32,
                            SkillGroupId = 4
                        },
                        new
                        {
                            SkillPoolId = 34,
                            SkillGroupId = 2
                        },
                        new
                        {
                            SkillPoolId = 34,
                            SkillGroupId = 3
                        },
                        new
                        {
                            SkillPoolId = 34,
                            SkillGroupId = 4
                        },
                        new
                        {
                            SkillPoolId = 36,
                            SkillGroupId = 2
                        });
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Auth.Account", b =>
                {
                    b.HasOne("DrawnFromSteel.Models.Auth.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Auth.Session", b =>
                {
                    b.HasOne("DrawnFromSteel.Models.Auth.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Static.Skill.Skill", b =>
                {
                    b.HasOne("DrawnFromSteel.Models.Static.Skill.SkillGroup", "SkillGroup")
                        .WithMany("Skills")
                        .HasForeignKey("SkillGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skill_skill_group_skill_group_id");

                    b.Navigation("SkillGroup");
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Static.Skill.SkillOptionPool", b =>
                {
                    b.HasOne("DrawnFromSteel.Models.Static.Skill.SkillOption", null)
                        .WithMany()
                        .HasForeignKey("SkillOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skill_option_pool_skill_option_skill_option_id");

                    b.HasOne("DrawnFromSteel.Models.Static.Skill.SkillPool", null)
                        .WithMany()
                        .HasForeignKey("SkillPoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skill_option_pool_skill_pool_skill_pool_id");
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Transient.Hero", b =>
                {
                    b.HasOne("DrawnFromSteel.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hero_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillPoolSkill", b =>
                {
                    b.HasOne("DrawnFromSteel.Models.Static.Skill.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skill_pool_skill_skill_skill_id");

                    b.HasOne("DrawnFromSteel.Models.Static.Skill.SkillPool", null)
                        .WithMany()
                        .HasForeignKey("SkillPoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skill_pool_skill_skill_pool_skill_pool_id");
                });

            modelBuilder.Entity("SkillPoolSkillGroup", b =>
                {
                    b.HasOne("DrawnFromSteel.Models.Static.Skill.SkillGroup", null)
                        .WithMany()
                        .HasForeignKey("SkillGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skill_pool_skill_group_skill_group_skill_group_id");

                    b.HasOne("DrawnFromSteel.Models.Static.Skill.SkillPool", null)
                        .WithMany()
                        .HasForeignKey("SkillPoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skill_pool_skill_group_skill_pool_skill_pool_id");
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Auth.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Static.Skill.SkillGroup", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
