// <auto-generated />
using System;
using DrawnFromSteel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DrawnFromSteel.Migrations
{
    [DbContext(typeof(DFSContext))]
    [Migration("20241211212438_AddSize")]
    partial class AddSize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrawnFromSteel.Models.Auth.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<int>("ExpiresAt")
                        .HasColumnType("integer")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_token");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_account_id");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("SessionState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_state");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_account_user_id");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("EmailVerified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Static.Ancestry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("SizeModifier")
                        .HasColumnType("integer")
                        .HasColumnName("size_modifier");

                    b.Property<int>("SizeSquares")
                        .HasColumnType("integer")
                        .HasColumnName("size_squares");

                    b.Property<int>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<string>("SubType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sub_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_ancestry");

                    b.ToTable("ancestry", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Devil"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Dragon Knight"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Dwarf"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 6,
                            SubType = "Wode",
                            Type = "Elf"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "High",
                            Type = "Elf"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            SizeModifier = 3,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Hakaan"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Human"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Memonek"
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Orc"
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            SizeModifier = 1,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Polder"
                        },
                        new
                        {
                            Id = 11,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Revenant"
                        },
                        new
                        {
                            Id = 12,
                            Description = "",
                            SizeModifier = 2,
                            SizeSquares = 1,
                            Speed = 5,
                            SubType = "",
                            Type = "Time Raider"
                        });
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Transient.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_hero");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_hero_user_id");

                    b.ToTable("hero", (string)null);
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Auth.Account", b =>
                {
                    b.HasOne("DrawnFromSteel.Models.Auth.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Transient.Hero", b =>
                {
                    b.HasOne("DrawnFromSteel.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hero_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DrawnFromSteel.Models.Auth.User", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
